### ISSUE TITLE
One-liner package references

### ISSUE THREAD

**Issue by geirsagberg** [jchadwick/nuget-reverse-package-search#5]
Looks like a really useful plugin!

I noticed in the example, a "full" `<PackageReference>` element is added. Is there any way to instead add a one-liner like this:

    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />

**Comment by jchadwick** [comment]
Great idea!  Thanks for pointing it out.  Will have it in shortly!
