### ISSUE TITLE
vscode can't install

### ISSUE THREAD

**Issue by BigBigPlant** [jchadwick/nuget-reverse-package-search#6]
Versioning information could not be retrieved from the NuGet package repository.palease try again.
why?

**Comment by BigBigPlant** [comment]
![1](https://user-images.githubusercontent.com/37919956/56851891-dd200080-6946-11e9-9a96-0ad714f7f614.PNG)

**Comment by cg1012** [comment]
hi bigPlant,
how do you fix the versioning problem?
